### ISSUE TITLE
Implement the `ysdk.features.LoadingAPI?.ready` function

### ISSUE THREAD

**Issue by aglitchman** [indiesoftby/defold-yagames#16]
Docs - https://yandex.ru/dev/games/doc/dg/sdk/sdk-gameready.html

**Comment by d954mas** [comment]
up:)

**Comment by aglitchman** [comment]
Fixed in https://github.com/indiesoftby/defold-yagames/commit/122b1b48bb95c6a74241a8bba0605d4ed5128ad7
